version: '2'
services:
  scrape-app:
    container_name: scrape-app
    build:
      context : .
      dockerfile: Dockerfile
    environment:
        TZ: "Asia/Tokyo"
    volumes:
        - ./scrape/src:/work
    depends_on:
        - postgres

  postgres:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_WASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: postgres-db
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    restart: always

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      - MB_DB_TYPE=${MB_DB_TYPE}
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - MB_DB_HOST=${MB_DB_HOST}
    restart: always

volumes:
  postgres-data:
    driver: local