version: '3'
services:
services:
  postgres:
    image: postgres:10.10
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data/:/var/lib/postgresql/data"
      - "./initdb:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=${MB_DB_DBNAME}
      - POSTGRES_USER=${MB_DB_USER}
      - POSTGRES_PASSWORD=${MB_DB_PASS}
      - TZ=Asia/Tokyo
  metabase:
    image: metabase/metabase:v0.32.10
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE}
      - MB_DB_HOST=${MB_DB_HOST}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_DBNAME=${MB_DB_DBNAME}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASS}
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - JAVA_TIMEZONE=Asia/Tokyo
    depends_on:
      - postgres

  scrape-app:
    build: .
    restart: always
    container_name: 'python3'
    volumes:
      - "./scrape:/opt/app"
    depends_on:
      - postgres
    tty: true